spring:
    application:
        name: backend

# H2 Database
    datasource:
        url: jdbc:h2:mem:/db 
        username: admin
        password: 

#JWT
api:
    security:
        token:
            secret: ${JTW_SECRET:my-secret-key}


#Admin
admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}
